
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxuuuzfndttyvbopeotc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dXV1emZuZHR0eXZib3Blb3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Nzk3OTMsImV4cCI6MjA2NDM1NTc5M30.5fO5hpO10Ch61BoK8sppL2ArhmujoqNjOBcHPaW4SvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
